In [ ]:
import os

# Check if already installed
if not os.path.exists('easyfinetune'):
    print("📥 Cloning EasyFineTune repository...")
    !git clone https://github.com/DevSsChar/Three-Tune.git

    print("\n📦 Installing dependencies...")
    %cd Three-Tune
    !pip install -e . -q

    print("\n✅ Installation complete!")
else:
    print("✅ EasyFineTune already installed!")
    %cd easyfinetune

📥 Cloning EasyFineTune repository...
Cloning into 'Three-Tune'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 92 (delta 24), reused 90 (delta 22), pack-reused 0 (from 0)
Receiving objects: 100% (92/92), 81.37 KiB | 6.78 MiB/s, done.
Resolving deltas: 100% (24/24), done.

📦 Installing dependencies...
/content/Three-Tune
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 13.8 MB/s eta 0:00:00
  Building editable for easyfinetune (pyproject.toml) ... done

✅ Installation complete!

In [ ]:
from easyfinetune.gpu import detect_gpu

gpu_info = detect_gpu()

print("\n" + "="*60)
print("🖥️  GPU DETECTION RESULTS")
print("="*60)
print(f"GPU Type: {gpu_info.gpu_type}")
print(f"GPU Name: {gpu_info.gpu_name}")
print(f"VRAM Available: {gpu_info.vram_gb:.1f} GB")
print(f"GPU Available: {gpu_info.is_available}")

if gpu_info.gpu_type == "colab_t4":
    print("\n✅ Perfect! Colab T4 detected.")
    print("   This is ideal for fine-tuning small-to-medium models.")
elif gpu_info.gpu_type == "cpu":
    print("\n⚠️  No GPU detected!")
    print("   Go to Runtime → Change runtime type → Select GPU")
else:
    print(f"\n✅ GPU detected: {gpu_info.gpu_name}")

print("="*60)

🔍 Detecting available compute hardware...
✅ Google Colab T4 GPU detected (14.6 GB VRAM)

============================================================
🖥️  GPU DETECTION RESULTS
============================================================
GPU Type: colab_t4
GPU Name: Tesla T4
VRAM Available: 14.6 GB
GPU Available: True

✅ Perfect! Colab T4 detected.
   This is ideal for fine-tuning small-to-medium models.
============================================================

In [ ]:
from easyfinetune.models import list_models

print("\n📚 AVAILABLE MODELS")
print("="*60)

for model in list_models():
    print(f"\n• {model.name}")
    print(f"  {model.description}")
    print(f"  Min VRAM: {model.min_vram_gb} GB | Context: {model.context_length} tokens")
    print(f"  HuggingFace: {model.hf_repo_id}")
    if model.requires_token:
        print(f"  ⚠️  Requires HuggingFace token")

print("\n" + "="*60)
print("💡 Tip: Use 'auto' to let EasyFineTune pick the best model for your GPU")

📚 AVAILABLE MODELS
============================================================

• phi-3-mini
  Microsoft Phi-3 Mini (3.8B params) - Fast and efficient
  Min VRAM: 8.0 GB | Context: 4096 tokens
  HuggingFace: microsoft/Phi-3-mini-4k-instruct

• llama-3.2-3b
  Meta Llama 3.2 3B - Latest small model from Meta
  Min VRAM: 8.0 GB | Context: 8192 tokens
  HuggingFace: meta-llama/Llama-3.2-3B-Instruct
  ⚠️  Requires HuggingFace token

• llama-3.1-8b
  Meta Llama 3.1 8B - Excellent quality/size tradeoff
  Min VRAM: 16.0 GB | Context: 8192 tokens
  HuggingFace: meta-llama/Meta-Llama-3.1-8B-Instruct
  ⚠️  Requires HuggingFace token

• mistral-7b
  Mistral 7B v0.3 - Strong open model
  Min VRAM: 14.0 GB | Context: 8192 tokens
  HuggingFace: mistralai/Mistral-7B-Instruct-v0.3

• gemma-2-9b
  Google Gemma 2 9B - High quality instruction model
  Min VRAM: 18.0 GB | Context: 8192 tokens
  HuggingFace: google/gemma-2-9b-it
  ⚠️  Requires HuggingFace token

• qwen-2.5-7b
  Qwen 2.5 7B - Excellent quality, long context (32k), no auth required
  Min VRAM: 14.0 GB | Context: 32768 tokens
  HuggingFace: Qwen/Qwen2.5-7B-Instruct

• qwen-2.5-3b
  Qwen 2.5 3B - Best for T4, long context (32k), no auth required
  Min VRAM: 8.0 GB | Context: 32768 tokens
  HuggingFace: Qwen/Qwen2.5-3B-Instruct

============================================================
💡 Tip: Use 'auto' to let EasyFineTune pick the best model for your GPU

In [ ]:
import json

# Create a sample sentiment dataset (50 examples)
sentiment_data = [
    # Positive examples
    {"text": "This movie was absolutely fantastic! I loved every minute of it.", "label": "positive"},
    {"text": "Amazing performance by the lead actor. Highly recommended!", "label": "positive"},
    {"text": "One of the best movies I've seen this year!", "label": "positive"},
    {"text": "Brilliant cinematography and storytelling. A masterpiece!", "label": "positive"},
    {"text": "Excellent film with great character development.", "label": "positive"},
    {"text": "Absolutely loved it! Will watch again.", "label": "positive"},
    {"text": "Captivating from start to finish. Truly outstanding!", "label": "positive"},
    {"text": "Remarkable film that exceeded all expectations.", "label": "positive"},
    {"text": "Superb direction and amazing soundtrack!", "label": "positive"},
    {"text": "Fantastic movie! One of my all-time favorites.", "label": "positive"},
    {"text": "Incredible story with perfect pacing.", "label": "positive"},
    {"text": "Beautifully crafted film. A must-watch!", "label": "positive"},
    {"text": "Outstanding performances across the board.", "label": "positive"},
    {"text": "Loved the plot twists and character arcs.", "label": "positive"},
    {"text": "Visually stunning and emotionally powerful.", "label": "positive"},
    {"text": "Best film I've seen in a long time!", "label": "positive"},
    {"text": "Masterful direction and stellar cast.", "label": "positive"},
    {"text": "Engaging, entertaining, and thought-provoking.", "label": "positive"},
    {"text": "A cinematic triumph! Absolutely brilliant.", "label": "positive"},
    {"text": "Every scene was perfection. Highly recommend!", "label": "positive"},
    {"text": "Wonderful movie with great messages.", "label": "positive"},
    {"text": "Exceeded expectations in every way.", "label": "positive"},
    {"text": "Phenomenal acting and beautiful visuals.", "label": "positive"},
    {"text": "Deeply moving and incredibly well-made.", "label": "positive"},
    {"text": "A gem of a film. Don't miss it!", "label": "positive"},

    # Negative examples
    {"text": "Terrible film. Complete waste of time and money.", "label": "negative"},
    {"text": "Boring and predictable. Not worth watching.", "label": "negative"},
    {"text": "Disappointing. Expected much better from this director.", "label": "negative"},
    {"text": "Worst movie ever. Couldn't even finish it.", "label": "negative"},
    {"text": "Poor acting and weak plot. Very underwhelming.", "label": "negative"},
    {"text": "Forgettable and generic. Nothing special.", "label": "negative"},
    {"text": "Dull and uninspiring. Save your money.", "label": "negative"},
    {"text": "Awful movie with terrible dialogue.", "label": "negative"},
    {"text": "Painfully slow and boring throughout.", "label": "negative"},
    {"text": "Complete disaster. Avoid at all costs.", "label": "negative"},
    {"text": "Poorly executed and confusing plot.", "label": "negative"},
    {"text": "Waste of talent. Script was terrible.", "label": "negative"},
    {"text": "Cringeworthy performances and bad editing.", "label": "negative"},
    {"text": "Overhyped and underwhelming disappointment.", "label": "negative"},
    {"text": "Boring from start to finish. Regret watching.", "label": "negative"},
    {"text": "Terrible pacing and weak storyline.", "label": "negative"},
    {"text": "Not entertaining at all. Very dull.", "label": "negative"},
    {"text": "Poor production quality and bad acting.", "label": "negative"},
    {"text": "Failed to deliver on its premise.", "label": "negative"},
    {"text": "Unoriginal and poorly written.", "label": "negative"},
    {"text": "Wasted two hours of my life.", "label": "negative"},
    {"text": "Shallow characters and predictable ending.", "label": "negative"},
    {"text": "Lacked depth and emotional connection.", "label": "negative"},
    {"text": "Messy plot and forgettable characters.", "label": "negative"},
    {"text": "Disappointing sequel. Lost the magic.", "label": "negative"},
]

# Save to file
with open('/content/sentiment_dataset.json', 'w') as f:
    json.dump(sentiment_data, f, indent=2)

print(f"✅ Created dataset with {len(sentiment_data)} examples")
print(f"📁 Saved to: /content/sentiment_dataset.json")
print(f"\n💡 This is a balanced dataset with equal positive/negative examples.")

✅ Created dataset with 50 examples
📁 Saved to: /content/sentiment_dataset.json

💡 This is a balanced dataset with equal positive/negative examples.

In [ ]:
from easyfinetune import tune

# Run validation only (no training)
result = tune(
    dataset="/content/vastu_training_dataset_complete.jsonl",
    validate_only=True
)

if result.success:
    print("\n✅ Dataset passed all quality checks!")
    print(f"Quality Score: {result.metrics.get('quality_score', 0):.1f}/10.0")
else:
    print("\n⚠️  Dataset has quality issues. Review the report above.")

======================================================================
🚀 EasyFineTune - Zero-to-Fine-Tuned in 3 Lines
======================================================================

📍 PHASE 1: Dataset Analysis
----------------------------------------------------------------------
📂 Loading dataset from vastu_training_dataset_complete.jsonl...
✓ Loaded 4034 examples
✓ Detected task type: instruction
✓ Split: 3428 train, 606 validation

🔍 Analyzing dataset quality...

============================================================
📊 DATASET QUALITY REPORT
============================================================

✅ Overall Quality Score: 10.0/10.0

✅ No issues found!

📈 Key Statistics:
  • Total examples: 4034
  • Train/Val split: 3428/606
  • Avg sequence length: ~14 tokens
  • Diversity score: 0.35

✅ Quality Check: PASSED
============================================================


✅ Dataset passed all quality checks!
Quality Score: 10.0/10.0

In [ ]:
from easyfinetune import tune

# This is it - 3 lines to fine-tune an LLM!
result = tune(
    dataset="/content/vastu_training_dataset_complete.jsonl",
    model="auto",  # Automatically picks best model for T4 (likely phi-3-mini)
    method="lora",  # Use LoRA for efficient fine-tuning
    num_epochs=2,  # Quick training (increase to 3-5 for better results)
)

# Check results
if result.success:
    print("\n" + "="*70)
    print("🎉 TRAINING SUCCESSFUL!")
    print("="*70)
    print(f"✅ Model saved to: {result.model_path}")
    print(f"✅ Validation loss: {result.metrics.get('eval_loss', 0):.3f}")
    print(f"✅ Training time: {result.total_time_minutes:.1f} minutes")
    print("\n📁 Output files:")
    for doc_type, path in result.docs.items():
        print(f"   • {doc_type}: {path}")
else:
    print(f"\n❌ Training failed: {result.message}")

======================================================================
🚀 EasyFineTune - Zero-to-Fine-Tuned in 3 Lines
======================================================================

📍 PHASE 1: Dataset Analysis
----------------------------------------------------------------------
📂 Loading dataset from vastu_training_dataset_complete.jsonl...
✓ Loaded 4034 examples
✓ Detected task type: instruction
✓ Split: 3428 train, 606 validation

🔍 Analyzing dataset quality...

============================================================
📊 DATASET QUALITY REPORT
============================================================

✅ Overall Quality Score: 10.0/10.0

✅ No issues found!

📈 Key Statistics:
  • Total examples: 4034
  • Train/Val split: 3428/606
  • Avg sequence length: ~14 tokens
  • Diversity score: 0.35

✅ Quality Check: PASSED
============================================================


📍 PHASE 2: Hardware Detection & Model Selection
----------------------------------------------------------------------

🔍 Detecting available compute hardware...
✅ Google Colab T4 GPU detected (14.6 GB VRAM)

🤖 Selecting optimal model...
✓ Colab T4 detected — selected qwen-2.5-3b (optimal for T4)
  Qwen 2.5 3B - Best for T4, long context (32k), no auth required
  Advantages: 32k context, no authentication, stable on T4

📍 PHASE 3: Training Setup
----------------------------------------------------------------------

⚙️  Configuring training setup...
✓ Auto-enabling QLoRA (4-bit) to prevent OOM on 14.6GB GPU
✓ Using QLoRA (4-bit quantization) to reduce memory usage
ℹ️  Memory calculation: 4.1GB model+overhead, 7.4GB available → batch_size=4
⚠️  Colab T4 detected: capping max_seq_length 2048 → 512 to prevent OOM
   (Activation memory scales with seq_length; 512 is safe for T4)

============================================================
⚙️  TRAINING CONFIGURATION
============================================================
Model: qwen-2.5-3b
Method: QLORA
Epochs: 2
Learning Rate: 2.00e-04
Batch Size: 4 (effective: 32)
Max Sequence Length: 512

LoRA Parameters:
  • Rank (r): 16
  • Alpha: 32
  • Dropout: 0.05
  • Target modules: q_proj, v_proj, k_proj, o_proj, gate_proj, up_proj, down_proj

Optimizations:
  • 4-bit quantization: ✓
  • Mixed precision (FP16): ✗
  • Gradient accumulation: 8 steps

Checkpoints: easyfinetune_output/checkpoints
============================================================


📍 PHASE 4: Model Loading
----------------------------------------------------------------------

📦 Loading model: Qwen/Qwen2.5-3B-Instruct...

🔍 Detecting available compute hardware...
✅ Google Colab T4 GPU detected (14.6 GB VRAM)
✓ 4-bit quantization configured (compute_dtype=torch.float16)

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

⚠️  Malformed rope_scaling config detected - disabling to prevent errors

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

`torch_dtype` is deprecated! Use `dtype` instead!

⚠️  Model loading with custom config failed: 'NoneType' object is not subscriptable
   Retrying with default config...

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

✓ Model loaded
✓ CUDA memory optimizations enabled
✓ Gradient checkpointing enabled via prepare_model_for_kbit_training
trainable params: 29,933,568 || all params: 3,115,872,256 || trainable%: 0.9607

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

✓ Tokenizer loaded


📍 PHASE 5: Dataset Preparation
----------------------------------------------------------------------
📝 Tokenizing dataset...

Tokenizing training data:   0%|          | 0/3428 [00:00<?, ? examples/s]

Tokenizing validation data:   0%|          | 0/606 [00:00<?, ? examples/s]

✓ Tokenization complete
  Training samples: 3428
  Validation samples: 606


📍 PHASE 6: Training
----------------------------------------------------------------------
Training qwen-2.5-3b with QLORA...
This will take approximately 1 minutes


🚀 Starting training...

📊 Epoch 0.09 · Step 10/216 · Loss: 5.043 · LR: 8.57e-05 · ETA: 22 min
📊 Epoch 0.19 · Step 20/216 · Loss: 2.992 · LR: 1.81e-04 · ETA: 21 min
📊 Epoch 0.28 · Step 30/216 · Loss: 1.634 · LR: 1.99e-04 · ETA: 20 min
📊 Epoch 0.37 · Step 40/216 · Loss: 1.243 · LR: 1.96e-04 · ETA: 19 min
📊 Epoch 0.47 · Step 50/216 · Loss: 0.990 · LR: 1.90e-04 · ETA: 18 min
📊 Epoch 0.47 · Step 50/216 · Loss: 0.000 · LR: 0.00e+00 · ETA: 20 min
✓ Validation Loss: 2.793
📊 Epoch 0.56 · Step 60/216 · Loss: 0.882 · LR: 1.82e-04 · ETA: 18 min
📊 Epoch 0.65 · Step 70/216 · Loss: 0.887 · LR: 1.72e-04 · ETA: 17 min
📊 Epoch 0.75 · Step 80/216 · Loss: 0.853 · LR: 1.59e-04 · ETA: 16 min
📊 Epoch 0.84 · Step 90/216 · Loss: 0.861 · LR: 1.46e-04 · ETA: 14 min
📊 Epoch 0.93 · Step 100/216 · Loss: 0.734 · LR: 1.31e-04 · ETA: 13 min
📊 Epoch 0.93 · Step 100/216 · Loss: 0.000 · LR: 0.00e+00 · ETA: 14 min
✓ Validation Loss: 3.516
💾 Checkpoint saved: checkpoint-100
📊 Epoch 1.02 · Step 110/216 · Loss: 0.740 · LR: 1.15e-04 · ETA: 13 min
📊 Epoch 1.11 · Step 120/216 · Loss: 0.645 · LR: 9.92e-05 · ETA: 11 min
📊 Epoch 1.21 · Step 130/216 · Loss: 0.642 · LR: 8.32e-05 · ETA: 10 min
📊 Epoch 1.30 · Step 140/216 · Loss: 0.639 · LR: 6.76e-05 · ETA: 9 min
📊 Epoch 1.39 · Step 150/216 · Loss: 0.684 · LR: 5.28e-05 · ETA: 8 min
📊 Epoch 1.39 · Step 150/216 · Loss: 0.000 · LR: 0.00e+00 · ETA: 8 min
✓ Validation Loss: 3.894
📊 Epoch 1.49 · Step 160/216 · Loss: 0.687 · LR: 3.93e-05 · ETA: 7 min
📊 Epoch 1.58 · Step 170/216 · Loss: 0.667 · LR: 2.73e-05 · ETA: 6 min
📊 Epoch 1.67 · Step 180/216 · Loss: 0.670 · LR: 1.72e-05 · ETA: 5 min
📊 Epoch 1.77 · Step 190/216 · Loss: 0.618 · LR: 9.31e-06 · ETA: 3 min
📊 Epoch 1.86 · Step 200/216 · Loss: 0.639 · LR: 3.73e-06 · ETA: 2 min
📊 Epoch 1.86 · Step 200/216 · Loss: 0.000 · LR: 0.00e+00 · ETA: 2 min
✓ Validation Loss: 3.975
💾 Checkpoint saved: checkpoint-200
📊 Epoch 1.95 · Step 210/216 · Loss: 0.698 · LR: 6.35e-07 · ETA: 1 min
💾 Checkpoint saved: checkpoint-216
📊 Epoch 2.00 · Step 216/216 · Loss: 0.000 · LR: 0.00e+00 · ETA: 0 min

✅ Training complete! Total time: 25 minutes


💾 Saving best model...
✓ Best model saved to: easyfinetune_output/best_model

📊 Evaluating best model...

📊 Epoch 2.00 · Step 216/216 · Loss: 0.000 · LR: 0.00e+00 · ETA: 0 min
✓ Validation Loss: 3.971
✓ Final validation loss: 3.971

📍 PHASE 7: Documentation
----------------------------------------------------------------------

📝 Generating documentation...
✓ README: easyfinetune_output/README.md
✓ Model Card: easyfinetune_output/MODEL_CARD.md
✓ Inference Script: easyfinetune_output/inference.py
✅ Documentation complete!


======================================================================
🎉 SUCCESS!
======================================================================
✅ Model fine-tuned and saved to: easyfinetune_output/best_model
✅ Final validation loss: 3.971
✅ Total time: 28.2 minutes

📁 Output Directory: easyfinetune_output
   • Model: easyfinetune_output/best_model
   • README: easyfinetune_output/README.md
   • Inference script: easyfinetune_output/inference.py

💡 Next Steps:
   1. Test your model: python easyfinetune_output/inference.py --prompt 'Your text'
   2. Review documentation: easyfinetune_output/README.md
   3. Share on HuggingFace Hub (optional)
======================================================================


======================================================================
🎉 TRAINING SUCCESSFUL!
======================================================================
✅ Model saved to: easyfinetune_output/best_model
✅ Validation loss: 3.971
✅ Training time: 28.2 minutes

📁 Output files:
   • readme: easyfinetune_output/README.md
   • model_card: easyfinetune_output/MODEL_CARD.md
   • inference_script: easyfinetune_output/inference.py

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch
import json
import os

print("Loading fine-tuned model...")

# Check if training completed successfully
if not result.success:
    print("❌ Training didn't complete successfully. Cannot load model.")
    print(f"Error: {result.message}")
    raise RuntimeError("Training failed - cannot proceed with model testing")

# Get paths from training result
model_path = result.model_path
print(f"📁 Model path: {model_path}")

# Get the actual base model used during training
# Check the config file that was saved
config_path = os.path.join(model_path, "adapter_config.json")
if os.path.exists(config_path):
    with open(config_path, 'r') as f:
        adapter_config = json.load(f)
        base_model_name = adapter_config.get('base_model_name_or_path')
        print(f"🔍 Detected base model: {base_model_name}")
else:
    # Fallback: try to get from result metadata
    base_model_name = result.metadata.get('model_hf_repo_id')
    if not base_model_name:
        print("❌ Cannot determine base model. Check adapter_config.json")
        raise RuntimeError("Base model not found in adapter config")
    print(f"🔍 Using model from training metadata: {base_model_name}")

try:
    print(f"\n📦 Loading base model: {base_model_name}")
    base_model = AutoModelForCausalLM.from_pretrained(
        base_model_name,
        device_map="auto",
        torch_dtype=torch.float16,
        trust_remote_code=True,
    )

    print(f"📦 Loading LoRA adapter from: {model_path}")
    model = PeftModel.from_pretrained(base_model, model_path)
    model.eval()

    print(f"📦 Loading tokenizer")
    tokenizer = AutoTokenizer.from_pretrained(base_model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    print("\n✅ Model loaded successfully!")

    # # Test prompts
    # test_prompts = [
    #     "Review: This is an amazing product! I love it.",
    #     "Review: Terrible quality. Very disappointed.",
    #     "Review: Not bad, but could be better.",
    # ]
    test_prompts = [
        "Is toilet in northwest good?",
        "I have master bedroom in north",
        "The toilet is in north east, is that good? if not suggest remedies"
    ]

    print("\n" + "="*60)
    print("🧪 TESTING FINE-TUNED MODEL")
    print("="*60)
    print(f"Model: {base_model_name}")
    print(f"Method: LoRA (fine-tuned adapter)")
    print("="*60)

    for i, prompt in enumerate(test_prompts, 1):
        print(f"\n[Test {i}/{len(test_prompts)}]")
        print(f"Prompt: {prompt}")
        print("-" * 60)

        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=250,
                temperature=0.7,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id,
            )

        generated = tokenizer.decode(outputs[0], skip_special_tokens=True)
        # Show only the new generated text (remove input prompt)
        response = generated[len(prompt):].strip()
        print(f"Response: {response}")

    print("\n" + "="*60)
    print("✅ Testing complete!")
    print("="*60)

except Exception as e:
    print(f"\n❌ Error loading model: {e}")
    print(f"\nDebug Info:")
    print(f"  • Model path: {model_path}")
    print(f"  • Base model: {base_model_name}")
    print(f"  • adapter_config.json exists: {os.path.exists(config_path)}")
    raise

Loading fine-tuned model...
📁 Model path: easyfinetune_output/best_model
🔍 Detected base model: Qwen/Qwen2.5-3B-Instruct

📦 Loading base model: Qwen/Qwen2.5-3B-Instruct

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

📦 Loading LoRA adapter from: easyfinetune_output/best_model
📦 Loading tokenizer

✅ Model loaded successfully!

============================================================
🧪 TESTING FINE-TUNED MODEL
============================================================
Model: Qwen/Qwen2.5-3B-Instruct
Method: LoRA (fine-tuned adapter)
============================================================

[Test 1/3]
Prompt: Is toilet in northwest good?
------------------------------------------------------------
Response: Where should toilet be? Any Vastu rules? According to Vastu Shastra, the ideal location for a toilet is typically in the Northeast corner of the house. Here are some key points to consider:

1. Northeast: This is considered the most auspicious location as it aligns with many Vastu principles.

2. Southwest: While not ideal, toilets in the southwest are better than in other directions.

3. Northwest: Not recommended due to water element conflicts with earth element (main house material).

4. Southeast: Poor choice as water element clashes with earth element.

5. Center or kitchen area: Very poor choices - avoid at all costs!

6. Northeast vs West: If you must choose between these two, NE is slightly better.

7. Toilet placement within room: Avoid placing toilet directly in bedroom or living room corners.

8. Door location: Keep toilet door separate from main entrance and kitchen.

9. Windows: Place toilet window on opposite side of house to main entrance.

10. Kitchen location: If toilet is in wrong direction, place kitchen near it for Vastu improvement.

Remember, Vastu is more about overall structure and flow rather than exact measurements. The goal is to create harmony and balance

[Test 2/3]
Prompt: I have master bedroom in north
------------------------------------------------------------
Response: . Which direction should I face while sleeping? Should I move the bed? What about kitchen? Where should it be? East or West? What about toilet? Where should it be? North or South? Based on Vastu, where should my study room be? East or West? What if it's a small house with limited space? Any specific recommendations for a small house? According to Vastu, where should my puja room be? East or West? What if I have limited space? How important is having a puja room? Based on Vastu, where should my main entrance be? Which direction is best? What if my house faces a road? Any specific recommendations? Let's address each of your questions regarding Vastu:

### Master Bedroom in North:
- **Facing Direction:** It's better to sleep with your head facing east or south. Sleeping with the head in the northern direction can cause health issues.
- **Bed Position:** If moving the bed is not possible, ensure that you use a headrest or pillow to face east or south.

### Kitchen:
- **Direction:** Ideally, the kitchen should be in the Northeast corner. However, if this is not feasible due to limited space, having the

[Test 3/3]
Prompt: The toilet is in north east, is that good? if not suggest remedies
------------------------------------------------------------
Response: ? The toilet in North-East is considered to be in the critical direction. According to Vastu principles, toilets should ideally be located in the Southwest or Southeast corners of a house. If your toilet is in the North-East, here are some remedies you can consider:

1. **Install a water fountain or fountain**: This helps purify the air and water. Place it in the Northwest corner of the toilet area.

2. **Keep a copper vessel with water**: Copper has purification properties according to Vastu. Keep a copper vessel filled with water at all times.

3. **Install a water purifier**: Ensure that the water used for bathing, washing hands, etc., is clean and purified.

4. **Lighting**: Use LED lights or other energy-efficient lighting fixtures. Avoid dark corners or areas where sunlight cannot reach.

5. **Plants**: Keep indoor plants like pothos, peace lily, or spider plant. They help purify the air.

6. **Feng Shui remedies**: Follow basic Feng Shui guidelines like keeping the toilet door closed, using light colors, and maintaining cleanliness.

7. **Consult a Vastu expert**: Sometimes professional guidance can provide specific solutions tailored to your situation.

8

============================================================
✅ Testing complete!
============================================================

In [ ]:
import os

output_dir = "./easyfinetune_output"

print("📁 Generated Files:\n")

files_to_check = [
    ("README.md", "Model documentation"),
    ("MODEL_CARD.md", "Model card with training details"),
    ("inference.py", "Ready-to-use inference script"),
]

for filename, description in files_to_check:
    filepath = os.path.join(output_dir, filename)
    if os.path.exists(filepath):
        size = os.path.getsize(filepath)
        print(f"✅ {filename} ({description})")
        print(f"   Size: {size:,} bytes")
        print(f"   Path: {filepath}\n")
    else:
        print(f"⚠️  {filename} not found\n")

# Show README preview
readme_path = os.path.join(output_dir, "README.md")
if os.path.exists(readme_path):
    print("\n" + "="*60)
    print("📄 README.md Preview (first 500 chars)")
    print("="*60)
    with open(readme_path, 'r') as f:
        content = f.read(500)
        print(content)
        print("\n... (see full file for more)")

📁 Generated Files:

✅ README.md (Model documentation)
   Size: 1,994 bytes
   Path: ./easyfinetune_output/README.md

✅ MODEL_CARD.md (Model card with training details)
   Size: 1,927 bytes
   Path: ./easyfinetune_output/MODEL_CARD.md

✅ inference.py (Ready-to-use inference script)
   Size: 2,577 bytes
   Path: ./easyfinetune_output/inference.py


============================================================
📄 README.md Preview (first 500 chars)
============================================================
# Fine-Tuned qwen-2.5-3b

Fine-tuned using [EasyFineTune](https://github.com/easyfinetune/easyfinetune)

## Model Details

- **Base Model:** [Qwen/Qwen2.5-3B-Instruct](https://huggingface.co/Qwen/Qwen2.5-3B-Instruct)
- **Fine-tuning Method:** QLORA
- **Training Date:** 2026-03-03

## Training Configuration

- **Epochs:** 2
- **Learning Rate:** 0.0002
- **Batch Size:** 4 (effective: 32)
- **Max Sequence Length:** 512

### LoRA Configuration
- **Rank (r):** 16
- **Alpha:** 32
- **Dropout:** 0.05
-

... (see full file for more)

In [ ]:
from google.colab import files
import shutil
import os
from tqdm import tqdm
import zipfile

print("📦 Preparing model for download...\n")

output_dir = "./easyfinetune_output"
output_zip_path = "/content/easyfinetune_model.zip"

# Calculate total size first
print("📏 Calculating size...")
total_size = 0
file_list = []
for root, dirs, files_in_dir in os.walk(output_dir):
    for file in files_in_dir:
        filepath = os.path.join(root, file)
        file_list.append(filepath)
        total_size += os.path.getsize(filepath)

print(f"📊 Total size: {total_size / (1024*1024):.1f} MB ({len(file_list)} files)")

# Create zip with progress bar
print("\n🗜️  Compressing files...")
with zipfile.ZipFile(output_zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    with tqdm(total=len(file_list), unit='file', desc='Zipping') as pbar:
        for filepath in file_list:
            arcname = os.path.relpath(filepath, os.path.dirname(output_dir))
            zipf.write(filepath, arcname)
            pbar.update(1)

# Check final zip size
zip_size_mb = os.path.getsize(output_zip_path) / (1024*1024)
print(f"\n✅ Model packaged successfully!")
print(f"📦 Compressed size: {zip_size_mb:.1f} MB")
print(f"📁 Location: {output_zip_path}")

# Download with size warning
if zip_size_mb > 200:
    print("\n⚠️  WARNING: File is very large (>200MB)")
    print("   Colab downloads may fail for large files.")
    print("   Consider using Google Drive instead (see next cell).")

    user_confirm = input("\nProceed with download anyway? (y/n): ")
    if user_confirm.lower() != 'y':
        print("❌ Download cancelled. Use Google Drive method below.")
    else:
        print("\n📥 Starting download...")
        try:
            files.download(output_zip_path)
            print("✅ Download started! Check your browser's download folder.")
        except Exception as e:
            print(f"❌ Download failed: {e}")
            print("💡 Try the Google Drive method in the next cell.")
elif zip_size_mb > 100:
    print("\n⚠️  Note: File is large (>100MB). Download may take a while.")
    print("📥 Starting download...")
    try:
        files.download(output_zip_path)
        print("✅ Download started! Check your browser's download folder.")
    except Exception as e:
        print(f"❌ Download failed: {e}")
        print("💡 Try the Google Drive method in the next cell.")
else:
    print("\n📥 Starting download...")
    try:
        files.download(output_zip_path)
        print("✅ Download started! Check your browser's download folder.")
    except Exception as e:
        print(f"❌ Download failed: {e}")
        print("💡 Try the Google Drive method in the next cell.")

📦 Preparing model for download...

📏 Calculating size...
📊 Total size: 479.1 MB (21 files)

🗜️  Compressing files...

Zipping: 100%|██████████| 21/21 [00:26<00:00,  1.24s/file]

✅ Model packaged successfully!
📦 Compressed size: 425.1 MB
📁 Location: /content/easyfinetune_model.zip

⚠️  WARNING: File is very large (>200MB)
   Colab downloads may fail for large files.
   Consider using Google Drive instead (see next cell).

Proceed with download anyway? (y/n): y

📥 Starting download...

✅ Download started! Check your browser's download folder.

Error below since didnt permit google drive, but do permit it

In [ ]:
# Mount Google Drive
from google.colab import drive
import shutil

print("📂 Mounting Google Drive...")
drive.mount('/content/drive')

# Copy to Drive
drive_path = '/content/drive/MyDrive/easyfinetune_models/'
os.makedirs(drive_path, exist_ok=True)

print(f"\n📤 Copying model to Google Drive...")
print(f"   Destination: {drive_path}")

# Copy the zip file
zip_source = "/content/easyfinetune_model.zip"
zip_dest = os.path.join(drive_path, "easyfinetune_model.zip")

if os.path.exists(zip_source):
    shutil.copy2(zip_source, zip_dest)
    print(f"\n✅ Model saved to Google Drive!")
    print(f"📁 Location: {zip_dest}")
    print(f"📊 Size: {os.path.getsize(zip_dest) / (1024*1024):.1f} MB")
    print("\n💡 Access it from: MyDrive/easyfinetune_models/easyfinetune_model.zip")
else:
    print("❌ Zip file not found. Run the previous cell first.")

📂 Mounting Google Drive...

MessageError: Error: credential propagation was unsuccessful

### CLI

In [ ]:
!easyfinetune models

📋 Available Models:

• phi-3-mini
  Microsoft Phi-3 Mini (3.8B params) - Fast and efficient
  Min VRAM: 8.0 GB | Context: 4096 tokens
  HF Repo: microsoft/Phi-3-mini-4k-instruct

• llama-3.2-3b
  Meta Llama 3.2 3B - Latest small model from Meta
  Min VRAM: 8.0 GB | Context: 8192 tokens
  HF Repo: meta-llama/Llama-3.2-3B-Instruct
  ⚠️  Requires HuggingFace access token

• llama-3.1-8b
  Meta Llama 3.1 8B - Excellent quality/size tradeoff
  Min VRAM: 16.0 GB | Context: 8192 tokens
  HF Repo: meta-llama/Meta-Llama-3.1-8B-Instruct
  ⚠️  Requires HuggingFace access token

• mistral-7b
  Mistral 7B v0.3 - Strong open model
  Min VRAM: 14.0 GB | Context: 8192 tokens
  HF Repo: mistralai/Mistral-7B-Instruct-v0.3

• gemma-2-9b
  Google Gemma 2 9B - High quality instruction model
  Min VRAM: 18.0 GB | Context: 8192 tokens
  HF Repo: google/gemma-2-9b-it
  ⚠️  Requires HuggingFace access token

• qwen-2.5-7b
  Qwen 2.5 7B - Excellent quality, long context (32k), no auth required
  Min VRAM: 14.0 GB | Context: 32768 tokens
  HF Repo: Qwen/Qwen2.5-7B-Instruct

• qwen-2.5-3b
  Qwen 2.5 3B - Best for T4, long context (32k), no auth required
  Min VRAM: 8.0 GB | Context: 32768 tokens
  HF Repo: Qwen/Qwen2.5-3B-Instruct

In [ ]:
!easyfinetune validate --dataset /content/vastu_training_dataset_complete.jsonl

🔍 Validating dataset...

======================================================================
🚀 EasyFineTune - Zero-to-Fine-Tuned in 3 Lines
======================================================================

📍 PHASE 1: Dataset Analysis
----------------------------------------------------------------------
📂 Loading dataset from vastu_training_dataset_complete.jsonl...
✓ Loaded 4034 examples
✓ Detected task type: instruction
✓ Split: 3428 train, 606 validation

🔍 Analyzing dataset quality...

============================================================
📊 DATASET QUALITY REPORT
============================================================

✅ Overall Quality Score: 10.0/10.0

✅ No issues found!

📈 Key Statistics:
  • Total examples: 4034
  • Train/Val split: 3428/606
  • Avg sequence length: ~14 tokens
  • Diversity score: 0.35

✅ Quality Check: PASSED
============================================================


✅ Dataset validation passed!
Quality score: 10.0/10.0

In [ ]:
# Complete EasyFineTune workflow

# 1. Import
from easyfinetune import tune

# 2. Fine-tune (that's it!)
result = tune(
    dataset="/content/sentiment_dataset.json",
    model="auto",      # Auto-select based on GPU
    method="lora",     # Use LoRA for efficient training
    num_epochs=2,      # Number of training epochs
)

# 3. Check results
print(f"Success: {result.success}")
print(f"Model: {result.model_path}")
print(f"Loss: {result.metrics.get('eval_loss', 0):.3f}")
print(f"Time: {result.total_time_minutes:.1f} min")

======================================================================
🚀 EasyFineTune - Zero-to-Fine-Tuned in 3 Lines
======================================================================

📍 PHASE 1: Dataset Analysis
----------------------------------------------------------------------
📂 Loading dataset from sentiment_dataset.json...
✓ Loaded 50 examples
✓ Detected task type: classification
✓ Split: 42 train, 8 validation

🔍 Analyzing dataset quality...

============================================================
📊 DATASET QUALITY REPORT
============================================================

✅ Overall Quality Score: 10.0/10.0

✅ No issues found!

📈 Key Statistics:
  • Total examples: 50
  • Train/Val split: 42/8
  • Avg sequence length: ~10 tokens
  • Diversity score: 0.96

✅ Quality Check: PASSED
============================================================


📍 PHASE 2: Hardware Detection & Model Selection
----------------------------------------------------------------------

🔍 Detecting available compute hardware...
✅ Google Colab T4 GPU detected (14.6 GB VRAM)

🤖 Selecting optimal model...
✓ Colab T4 detected — selected qwen-2.5-3b (optimal for T4)
  Qwen 2.5 3B - Best for T4, long context (32k), no auth required
  Advantages: 32k context, no authentication, stable on T4

📍 PHASE 3: Training Setup
----------------------------------------------------------------------

⚙️  Configuring training setup...
✓ Auto-enabling QLoRA (4-bit) to prevent OOM on 14.6GB GPU
✓ Using QLoRA (4-bit quantization) to reduce memory usage
ℹ️  Memory calculation: 4.1GB model+overhead, 7.4GB available → batch_size=4
⚠️  Colab T4 detected: capping max_seq_length 2048 → 512 to prevent OOM
   (Activation memory scales with seq_length; 512 is safe for T4)

============================================================
⚙️  TRAINING CONFIGURATION
============================================================
Model: qwen-2.5-3b
Method: QLORA
Epochs: 2
Learning Rate: 2.00e-04
Batch Size: 4 (effective: 32)
Max Sequence Length: 512

LoRA Parameters:
  • Rank (r): 16
  • Alpha: 32
  • Dropout: 0.05
  • Target modules: q_proj, v_proj, k_proj, o_proj, gate_proj, up_proj, down_proj

Optimizations:
  • 4-bit quantization: ✓
  • Mixed precision (FP16): ✗
  • Gradient accumulation: 8 steps

Checkpoints: easyfinetune_output/checkpoints
============================================================


📍 PHASE 4: Model Loading
----------------------------------------------------------------------

📦 Loading model: Qwen/Qwen2.5-3B-Instruct...

🔍 Detecting available compute hardware...
✅ Google Colab T4 GPU detected (14.6 GB VRAM)
✓ 4-bit quantization configured (compute_dtype=torch.float16)
⚠️  Malformed rope_scaling config detected - disabling to prevent errors
⚠️  Model loading with custom config failed: 'NoneType' object is not subscriptable
   Retrying with default config...

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

✓ Model loaded
✓ CUDA memory optimizations enabled
✓ Gradient checkpointing enabled via prepare_model_for_kbit_training
trainable params: 29,933,568 || all params: 3,115,872,256 || trainable%: 0.9607
✓ Tokenizer loaded


📍 PHASE 5: Dataset Preparation
----------------------------------------------------------------------
📝 Tokenizing dataset...

Tokenizing training data:   0%|          | 0/42 [00:00<?, ? examples/s]

Tokenizing validation data:   0%|          | 0/8 [00:00<?, ? examples/s]

✓ Tokenization complete
  Training samples: 42
  Validation samples: 8


📍 PHASE 6: Training
----------------------------------------------------------------------
Training qwen-2.5-3b with QLORA...
This will take approximately 0 minutes


🚀 Starting training...

💾 Checkpoint saved: checkpoint-4
📊 Epoch 2.00 · Step 4/4 · Loss: 0.000 · LR: 0.00e+00 · ETA: 0 min

✅ Training complete! Total time: 0 minutes


💾 Saving best model...
✓ Best model saved to: easyfinetune_output/best_model

📊 Evaluating best model...

📊 Epoch 2.00 · Step 4/4 · Loss: 0.000 · LR: 0.00e+00 · ETA: 0 min
✓ Validation Loss: 5.051
✓ Final validation loss: 5.051

📍 PHASE 7: Documentation
----------------------------------------------------------------------

📝 Generating documentation...
✓ README: easyfinetune_output/README.md
✓ Model Card: easyfinetune_output/MODEL_CARD.md
✓ Inference Script: easyfinetune_output/inference.py
✅ Documentation complete!


======================================================================
🎉 SUCCESS!
======================================================================
✅ Model fine-tuned and saved to: easyfinetune_output/best_model
✅ Final validation loss: 5.051
✅ Total time: 0.9 minutes

📁 Output Directory: easyfinetune_output
   • Model: easyfinetune_output/best_model
   • README: easyfinetune_output/README.md
   • Inference script: easyfinetune_output/inference.py

💡 Next Steps:
   1. Test your model: python easyfinetune_output/inference.py --prompt 'Your text'
   2. Review documentation: easyfinetune_output/README.md
   3. Share on HuggingFace Hub (optional)
======================================================================

Success: True
Model: easyfinetune_output/best_model
Loss: 5.051
Time: 0.9 min

In [ ]:
!python easyfinetune_output/inference.py --prompt 'Review: Not bad, but could be better.'

Loading model...
`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100% 434/434 [00:20<00:00, 21.38it/s, Materializing param=model.norm.weight]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Some parameters are on the meta device because they were offloaded to the cpu.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/peft/config.py", line 317, in _get_peft_type
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py", line 85, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py", line 135, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars, '-', '_' or '.'. The name cannot start or end with '-' or '.' and the maximum length is 96: './best_model'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Three-Tune/easyfinetune_output/inference.py", line 99, in <module>
    main()
  File "/content/Three-Tune/easyfinetune_output/inference.py", line 78, in main
    model, tokenizer = load_model(args.model_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/Three-Tune/easyfinetune_output/inference.py", line 27, in load_model
    model = PeftModel.from_pretrained(base_model, model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/peft/peft_model.py", line 459, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig._get_peft_type(model_id, **hf_kwargs)].from_pretrained(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/peft/config.py", line 323, in _get_peft_type
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{model_id}'")
ValueError: Can't find 'adapter_config.json' at './best_model'